"use client";

import { use, useEffect, useState } from "react";
import Link from "next/link";
import { Loader2 } from "lucide-react";
import { SupplementFactsPanel } from "@/components/formulations/SupplementFactsPanel";
import type { Formulation } from "@/lib/formulations/types";

export default function PublicSharePage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = use(params);
  const [formulation, setFormulation] = useState<Formulation | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch(`/api/f/${token}`, { cache: "no-store" });
        const json = await res.json();
        if (!res.ok) throw new Error(json.error ?? "Failed to load");
        if (!cancelled) setFormulation(json.formulation);
      } catch (e) {
        if (!cancelled) setError(e instanceof Error ? e.message : "Failed to load");
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, [token]);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-gray-50">
        <Loader2 className="size-5 animate-spin text-brand" />
      </div>
    );
  }

  if (error || !formulation) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-gray-50 px-4 text-center">
        <p className="text-[15px] font-medium text-gray-900">This formulation is not available</p>
        <p className="mt-1.5 text-[13px] text-gray-500">{error ?? "The link may have expired or been revoked."}</p>
        <Link href="/" className="mt-4 text-[12px] font-medium text-brand hover:underline">
          Visit FormLayer
        </Link>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-10">
      <div className="mx-auto max-w-[820px] px-4">
        {/* Header */}
        <div className="mb-6 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <span className="size-2 rounded-full bg-brand" />
            <span className="text-[14px] font-semibold text-gray-950">FormLayer</span>
          </Link>
          <Link
            href="/sign-up"
            className="rounded-full bg-gray-950 px-4 py-2 text-[12px] font-medium text-white transition hover:bg-gray-800"
          >
            View on FormLayer
          </Link>
        </div>

        <div className="rounded-2xl border border-black/[0.06] bg-white p-8 shadow-[0_1px_4px_rgba(0,0,0,0.04)]">
          <p className="text-[11px] font-semibold uppercase tracking-widest text-gray-400">Shared formulation</p>
          <h1 className="mt-2 text-[26px] font-semibold tracking-[-0.02em] text-gray-950">{formulation.name}</h1>
          {formulation.description && (
            <p className="mt-3 text-[13px] leading-relaxed text-gray-700">{formulation.description}</p>
          )}

          <div className="mt-6 grid gap-6 md:grid-cols-[auto_1fr]">
            <div>
              <SupplementFactsPanel formulation={formulation} />
            </div>
            <div>
              <h2 className="text-[12px] font-semibold uppercase tracking-widest text-gray-400">Ingredients</h2>
              <table className="mt-3 w-full text-[12px]">
                <tbody>
                  {formulation.ingredients.map((ing, i) => (
                    <tr key={ing.id || i} className="border-b border-black/[0.05]">
                      <td className="py-2 font-medium text-gray-900">{ing.name || "—"}</td>
                      <td className="py-2 font-mono text-right text-gray-700">
                        {ing.dose || "—"}{ing.dose ? ` ${ing.unit || "mg"}` : ""}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <div className="mt-8 rounded-xl border border-brand/15 bg-brand/[0.04] p-5">
            <p className="text-[13px] font-semibold text-gray-950">Building a supplement product?</p>
            <p className="mt-1 text-[12px] text-gray-600">
              FormLayer is the operating system for nutraceutical formulation, compliance, and manufacturer handoff.
            </p>
            <Link
              href="/sign-up"
              className="mt-3 inline-flex rounded-lg bg-gray-950 px-4 py-2 text-[12px] font-medium text-white transition hover:bg-gray-800"
            >
              Create a free account
            </Link>
          </div>
        </div>

        <p className="mt-6 text-center text-[11px] text-gray-400">
          Generated by FormLayer · This dossier is for product development purposes. Statements have not been evaluated by the FDA.
        </p>
      </div>
    </div>
  );
}
